#pragma config(Sensor, in6,    lineTrackerLeft, sensorLineFollower)
#pragma config(Sensor, in7,    lineTrackerRight, sensorLineFollower)
#pragma config(Sensor, dgtl10, limitSwitch,    sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port9,           thingMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	clearTimer(T1); //it was spelled with "c" twice, while once with "C"
	//Create and set the threshold for the Line Tracking Sensors.
	//LineTrackers return 0-4095, where high values are dark and low values are light.
	int threshold;
	threshold = 2500;

	//Loop forever.
	while(true)
	{
		////Go forward to clear the box tape (yellow is very similar to the retreflective) to not confuse the line follower
		//if(time1[T1] <= 500)
		//{
		//	motor[leftMotor]  = 40;
		//	motor[rightMotor] = 40;
		//}
		////Once the tape has been cleared, follow the line.
		//else
		//{
			//If both sensors see dark...
			if(SensorValue(lineTrackerLeft ) > threshold && SensorValue(lineTrackerRight) > threshold)
			{
				//...move forward.
				motor[leftMotor]  = 40;
				motor[rightMotor] = 40;
			}
			//If both sensors see light... (this is to clear the yellow tape in the starting box)
			else if(SensorValue(lineTrackerLeft ) < threshold && SensorValue(lineTrackerRight) < threshold)
			{
				//...move forward.
				motor[leftMotor]  = 40;
				motor[rightMotor] = 40;
			}
			//If the left sensor sees light...
			else if(SensorValue(lineTrackerLeft) < threshold)
			{
				//...counter-steer to the left.
				motor[leftMotor]  = 0;
				motor[rightMotor] = 40;
			}
			//If the right sensor sees light...
			else if(SensorValue(lineTrackerRight) < threshold)
			{
				//...counter-steer to the right.
				motor[leftMotor]  = 40;
				motor[rightMotor] = 0;
			}

			//If switch is pressed...
			if(SensorValue(limitSwitch)){
				//...stop moving
				motor[leftMotor]  = 0;
				motor[rightMotor] = 0;
			}
		//}
	}
}
