#pragma config(Sensor, in6,    lineTrackerLeft, sensorLineFollower)
#pragma config(Sensor, in7,    lineTrackerRight, sensorLineFollower)
#pragma config(Sensor, dgtl10, limitSwitch,    sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port2,           leftLinkMotor, tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port9,           rightLinkMotor, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)


//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(0) //this looks like where you would set for how long events last
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                         Driver Skills Template
//
// This is a template for the driver skills competition. It is identical in structure to
// the standard competition template except that the two "#pragma' statements above (and
// copied below) adjust the time limits for the competition.
//				#pragma autonomousDuration(0)
//				#pragma userControlDuration(60)
// The autonomous duration for "Driver Skills" is zero; i.e. there is no autonomous phase.
// The user control duration is 60 seconds
//
// NOTE: The above two pragmas only impact the Crystal implementation. For systems using
//       VEXNET, the VEXNET system ignores these statements as it has the durations
//       for the competition built-in.
//
// Whenever this user program is run, the duration is automatically sent to the VEX master
// processor. The master CPU will only accept these commands once per power=on cycle. So, it's
// best to power cycle your VEX to ensure that they get recognized in case you were
// previously running a standard competition program with different durations.
//
// Testing Via Crystals:
// ====================
//
// The procedure to test a Driver Skills program using the crystals is as follows:
//
// 1. Turn off power to the Crystal transmitter/joysticks.
//
// 2. Turn on your VEX so that the Driver Skills program is running.
//
// 3. Driver skills program segment of your program will start running. At the end of 60
//    seconds the VEX Master CPU will turn off the motors.
//
// 4. Repeat the above sequence
//
//
// Testing Via VEXNET Using VEXNET Competition Switch
// ==================================================
//
// The procedure to test a Driver Skills program using VEXNET Competition Switch is as follows:
//
// 1. Set the two switches on the Competition switch to "DISABLE" and "USER CONTROL"
//
// 2. Start the Driver skills program
//
// 3. Set Switch to ENABLE from DISABLE
//
// 4. You need to manually time the 60 second duration.
//
// 5. Set Switch to DISABLE
//
// 6. Repeat from step (3) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
//
// Testing Via VEXNET Using ROBOTC IDE
// ==================================================
//
// It is not necessary to own a VEXNET switch. ROBOTC has a test window that allows the same functionality.
// The test window has three buttons for "DISABLE", "AUTONOMOUS", "USER CONTROL".
//
// 1. Open the ROBOTC Debugger. Then open the "Competition Control" Debugger window.
//
// 2. Start your Driver Skills program running.
//
// 3. Click the "DISABLED" button on the "Competition Control" window.
//
// 4. Click the "USER CONTROL" button on the "Competition Control" window.
//
// 5. You need to manually time the 60 second duration.
//
// 6. Click the "DISABLED" button on the "Competition Control" window.
//
// 7. Repeat from step (4) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// The "Driver Skills" competition has no autonomous phase. Simply leave the following
// placeholder.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	clearTimer(T1); //it was spelled with "c" twice, while once with "C"
	//Create and set the threshold for the Line Tracking Sensors.
	//LineTrackers return 0-4095, where high values are dark and low values are light.
	int lfThreshold;
	lfthreshold = 2500;

	//Loop forever.
	while(true)
	{
		////Go forward to clear the box tape (yellow is very similar to the retreflective) to not confuse the line follower
		//if(time1[T1] <= 500)
		//{
		//	motor[leftMotor]  = 40;
		//	motor[rightMotor] = 40;
		//}
		////Once the tape has been cleared, follow the line.
		//else
		//{
			//If both sensors see dark...
			if(SensorValue(lineTrackerLeft ) > threshold && SensorValue(lineTrackerRight) > threshold)
			{
				//...move forward.
				motor[leftMotor]  = 40; //127 is full forward, -127 is full reverse or it might be out of 100%
				motor[rightMotor] = 40;
			}
			//If both sensors see light... (this is to clear the yellow tape in the starting box)
			else if(SensorValue(lineTrackerLeft ) < threshold && SensorValue(lineTrackerRight) < threshold)
			{
				//...move forward.
				motor[leftMotor]  = 40;
				motor[rightMotor] = 40;
			}
			//If the left sensor sees light...
			else if(SensorValue(lineTrackerLeft) < threshold) //could be sersorValue[sensorName]
			{
				//...counter-steer to the left.
				motor[leftMotor]  = 0;
				motor[rightMotor] = 40;
			}
			//If the right sensor sees light...
			else if(SensorValue(lineTrackerRight) < threshold)
			{
				//...counter-steer to the right.
				motor[leftMotor]  = 40;
				motor[rightMotor] = 0;
			}

			//If switch is pressed...
			if(SensorValue(limitSwitch)){
				//...stop moving
				motor[leftMotor]  = 0;
				motor[rightMotor] = 0;
			}
		//}
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................

		//while(true)
		//{
			motor[leftMotor]  = vexRT[Ch3];   // Left Joystick Y value
			motor[rightMotor] = vexRT[Ch2];   // Right Joystick Y value

			//if button 5D is pressed, raise
			if(vexRT[Btn5D] == 1)
			{
				setMultipleMotors(80, motor[leftLinkMotor], motor[rightLinkMotor]);
			}
			//if button 6D is pressed, lower
			else if (vexRT[Btn6D] == 1)
			{
				setMultipleMotors(-80, motor[leftLinkMotor], motor[rightLinkMotor]);
			}
			//otherwise, do not do anything
			else
			{
				setMultipleMotors(0, motor[leftLinkMotor], motor[rightLinkMotor]);
			}
		//}
	}
}
