#pragma config(Sensor, port3,  DIST,           sensorVexIQ_Distance)
#pragma config(Motor,  motor1,          LEFT,          tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          RIGHT,         tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*
All distance return values are in meters.
*/
task main()
{
	motor[LEFT] = 100;
	motor[RIGHT] = 100;

	int lineFollower1 = SensorValue(port7);
	int lineFollower2 = SensorValue(port3);
	sleep(2000);

	motor[LEFT] = 100;
	motor[RIGHT] = 100;

	sleep(10000);
}
